/*
 * Generated by gdbus-codegen 2.40.2. DO NOT EDIT.
 *
 * The license of this code is the same as for the source it was derived from.
 */

#ifndef __AUTO_GEN_INTERFACE_H__
#define __AUTO_GEN_INTERFACE_H__

#include <gio/gio.h>

G_BEGIN_DECLS


/* ------------------------------------------------------------------------ */
/* Declarations for org.tizen.system.deviced.display */

#define _AUTO_GEN_TYPE_ORG_TIZEN_SYSTEM_DEVICED_DISPLAY (_auto_gen_org_tizen_system_deviced_display_get_type ())
#define _AUTO_GEN_ORG_TIZEN_SYSTEM_DEVICED_DISPLAY(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), _AUTO_GEN_TYPE_ORG_TIZEN_SYSTEM_DEVICED_DISPLAY, _auto_genOrgTizenSystemDevicedDisplay))
#define _AUTO_GEN_IS_ORG_TIZEN_SYSTEM_DEVICED_DISPLAY(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), _AUTO_GEN_TYPE_ORG_TIZEN_SYSTEM_DEVICED_DISPLAY))
#define _AUTO_GEN_ORG_TIZEN_SYSTEM_DEVICED_DISPLAY_GET_IFACE(o) (G_TYPE_INSTANCE_GET_INTERFACE ((o), _AUTO_GEN_TYPE_ORG_TIZEN_SYSTEM_DEVICED_DISPLAY, _auto_genOrgTizenSystemDevicedDisplayIface))

struct __auto_genOrgTizenSystemDevicedDisplay;
typedef struct __auto_genOrgTizenSystemDevicedDisplay _auto_genOrgTizenSystemDevicedDisplay;
typedef struct __auto_genOrgTizenSystemDevicedDisplayIface _auto_genOrgTizenSystemDevicedDisplayIface;

struct __auto_genOrgTizenSystemDevicedDisplayIface
{
  GTypeInterface parent_iface;

  gboolean (*handle_current_brightness) (
    _auto_genOrgTizenSystemDevicedDisplay *object,
    GDBusMethodInvocation *invocation);

  gboolean (*handle_custom_brightness) (
    _auto_genOrgTizenSystemDevicedDisplay *object,
    GDBusMethodInvocation *invocation);

  gboolean (*handle_hold_brightness) (
    _auto_genOrgTizenSystemDevicedDisplay *object,
    GDBusMethodInvocation *invocation,
    gint arg_brightness);

  gboolean (*handle_lockstate) (
    _auto_genOrgTizenSystemDevicedDisplay *object,
    GDBusMethodInvocation *invocation,
    const gchar *arg_state,
    const gchar *arg_option1,
    const gchar *arg_option2,
    gint arg_timeout);

  gboolean (*handle_release_brightness) (
    _auto_genOrgTizenSystemDevicedDisplay *object,
    GDBusMethodInvocation *invocation);

  gboolean (*handle_unlockstate) (
    _auto_genOrgTizenSystemDevicedDisplay *object,
    GDBusMethodInvocation *invocation,
    const gchar *arg_state,
    const gchar *arg_option);

};

GType _auto_gen_org_tizen_system_deviced_display_get_type (void) G_GNUC_CONST;

GDBusInterfaceInfo *_auto_gen_org_tizen_system_deviced_display_interface_info (void);
guint _auto_gen_org_tizen_system_deviced_display_override_properties (GObjectClass *klass, guint property_id_begin);


/* D-Bus method call completion functions: */
void _auto_gen_org_tizen_system_deviced_display_complete_lockstate (
    _auto_genOrgTizenSystemDevicedDisplay *object,
    GDBusMethodInvocation *invocation,
    gint result);

void _auto_gen_org_tizen_system_deviced_display_complete_unlockstate (
    _auto_genOrgTizenSystemDevicedDisplay *object,
    GDBusMethodInvocation *invocation,
    gint result);

void _auto_gen_org_tizen_system_deviced_display_complete_release_brightness (
    _auto_genOrgTizenSystemDevicedDisplay *object,
    GDBusMethodInvocation *invocation,
    gint result);

void _auto_gen_org_tizen_system_deviced_display_complete_hold_brightness (
    _auto_genOrgTizenSystemDevicedDisplay *object,
    GDBusMethodInvocation *invocation,
    gint result);

void _auto_gen_org_tizen_system_deviced_display_complete_current_brightness (
    _auto_genOrgTizenSystemDevicedDisplay *object,
    GDBusMethodInvocation *invocation,
    gint result);

void _auto_gen_org_tizen_system_deviced_display_complete_custom_brightness (
    _auto_genOrgTizenSystemDevicedDisplay *object,
    GDBusMethodInvocation *invocation,
    gint result);



/* D-Bus method calls: */
void _auto_gen_org_tizen_system_deviced_display_call_lockstate (
    _auto_genOrgTizenSystemDevicedDisplay *proxy,
    const gchar *arg_state,
    const gchar *arg_option1,
    const gchar *arg_option2,
    gint arg_timeout,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean _auto_gen_org_tizen_system_deviced_display_call_lockstate_finish (
    _auto_genOrgTizenSystemDevicedDisplay *proxy,
    gint *out_result,
    GAsyncResult *res,
    GError **error);

gboolean _auto_gen_org_tizen_system_deviced_display_call_lockstate_sync (
    _auto_genOrgTizenSystemDevicedDisplay *proxy,
    const gchar *arg_state,
    const gchar *arg_option1,
    const gchar *arg_option2,
    gint arg_timeout,
    gint *out_result,
    GCancellable *cancellable,
    GError **error);

void _auto_gen_org_tizen_system_deviced_display_call_unlockstate (
    _auto_genOrgTizenSystemDevicedDisplay *proxy,
    const gchar *arg_state,
    const gchar *arg_option,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean _auto_gen_org_tizen_system_deviced_display_call_unlockstate_finish (
    _auto_genOrgTizenSystemDevicedDisplay *proxy,
    gint *out_result,
    GAsyncResult *res,
    GError **error);

gboolean _auto_gen_org_tizen_system_deviced_display_call_unlockstate_sync (
    _auto_genOrgTizenSystemDevicedDisplay *proxy,
    const gchar *arg_state,
    const gchar *arg_option,
    gint *out_result,
    GCancellable *cancellable,
    GError **error);

void _auto_gen_org_tizen_system_deviced_display_call_release_brightness (
    _auto_genOrgTizenSystemDevicedDisplay *proxy,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean _auto_gen_org_tizen_system_deviced_display_call_release_brightness_finish (
    _auto_genOrgTizenSystemDevicedDisplay *proxy,
    gint *out_result,
    GAsyncResult *res,
    GError **error);

gboolean _auto_gen_org_tizen_system_deviced_display_call_release_brightness_sync (
    _auto_genOrgTizenSystemDevicedDisplay *proxy,
    gint *out_result,
    GCancellable *cancellable,
    GError **error);

void _auto_gen_org_tizen_system_deviced_display_call_hold_brightness (
    _auto_genOrgTizenSystemDevicedDisplay *proxy,
    gint arg_brightness,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean _auto_gen_org_tizen_system_deviced_display_call_hold_brightness_finish (
    _auto_genOrgTizenSystemDevicedDisplay *proxy,
    gint *out_result,
    GAsyncResult *res,
    GError **error);

gboolean _auto_gen_org_tizen_system_deviced_display_call_hold_brightness_sync (
    _auto_genOrgTizenSystemDevicedDisplay *proxy,
    gint arg_brightness,
    gint *out_result,
    GCancellable *cancellable,
    GError **error);

void _auto_gen_org_tizen_system_deviced_display_call_current_brightness (
    _auto_genOrgTizenSystemDevicedDisplay *proxy,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean _auto_gen_org_tizen_system_deviced_display_call_current_brightness_finish (
    _auto_genOrgTizenSystemDevicedDisplay *proxy,
    gint *out_result,
    GAsyncResult *res,
    GError **error);

gboolean _auto_gen_org_tizen_system_deviced_display_call_current_brightness_sync (
    _auto_genOrgTizenSystemDevicedDisplay *proxy,
    gint *out_result,
    GCancellable *cancellable,
    GError **error);

void _auto_gen_org_tizen_system_deviced_display_call_custom_brightness (
    _auto_genOrgTizenSystemDevicedDisplay *proxy,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean _auto_gen_org_tizen_system_deviced_display_call_custom_brightness_finish (
    _auto_genOrgTizenSystemDevicedDisplay *proxy,
    gint *out_result,
    GAsyncResult *res,
    GError **error);

gboolean _auto_gen_org_tizen_system_deviced_display_call_custom_brightness_sync (
    _auto_genOrgTizenSystemDevicedDisplay *proxy,
    gint *out_result,
    GCancellable *cancellable,
    GError **error);



/* ---- */

#define _AUTO_GEN_TYPE_ORG_TIZEN_SYSTEM_DEVICED_DISPLAY_PROXY (_auto_gen_org_tizen_system_deviced_display_proxy_get_type ())
#define _AUTO_GEN_ORG_TIZEN_SYSTEM_DEVICED_DISPLAY_PROXY(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), _AUTO_GEN_TYPE_ORG_TIZEN_SYSTEM_DEVICED_DISPLAY_PROXY, _auto_genOrgTizenSystemDevicedDisplayProxy))
#define _AUTO_GEN_ORG_TIZEN_SYSTEM_DEVICED_DISPLAY_PROXY_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), _AUTO_GEN_TYPE_ORG_TIZEN_SYSTEM_DEVICED_DISPLAY_PROXY, _auto_genOrgTizenSystemDevicedDisplayProxyClass))
#define _AUTO_GEN_ORG_TIZEN_SYSTEM_DEVICED_DISPLAY_PROXY_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), _AUTO_GEN_TYPE_ORG_TIZEN_SYSTEM_DEVICED_DISPLAY_PROXY, _auto_genOrgTizenSystemDevicedDisplayProxyClass))
#define _AUTO_GEN_IS_ORG_TIZEN_SYSTEM_DEVICED_DISPLAY_PROXY(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), _AUTO_GEN_TYPE_ORG_TIZEN_SYSTEM_DEVICED_DISPLAY_PROXY))
#define _AUTO_GEN_IS_ORG_TIZEN_SYSTEM_DEVICED_DISPLAY_PROXY_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), _AUTO_GEN_TYPE_ORG_TIZEN_SYSTEM_DEVICED_DISPLAY_PROXY))

typedef struct __auto_genOrgTizenSystemDevicedDisplayProxy _auto_genOrgTizenSystemDevicedDisplayProxy;
typedef struct __auto_genOrgTizenSystemDevicedDisplayProxyClass _auto_genOrgTizenSystemDevicedDisplayProxyClass;
typedef struct __auto_genOrgTizenSystemDevicedDisplayProxyPrivate _auto_genOrgTizenSystemDevicedDisplayProxyPrivate;

struct __auto_genOrgTizenSystemDevicedDisplayProxy
{
  /*< private >*/
  GDBusProxy parent_instance;
  _auto_genOrgTizenSystemDevicedDisplayProxyPrivate *priv;
};

struct __auto_genOrgTizenSystemDevicedDisplayProxyClass
{
  GDBusProxyClass parent_class;
};

GType _auto_gen_org_tizen_system_deviced_display_proxy_get_type (void) G_GNUC_CONST;

void _auto_gen_org_tizen_system_deviced_display_proxy_new (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data);
_auto_genOrgTizenSystemDevicedDisplay *_auto_gen_org_tizen_system_deviced_display_proxy_new_finish (
    GAsyncResult        *res,
    GError             **error);
_auto_genOrgTizenSystemDevicedDisplay *_auto_gen_org_tizen_system_deviced_display_proxy_new_sync (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error);

void _auto_gen_org_tizen_system_deviced_display_proxy_new_for_bus (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data);
_auto_genOrgTizenSystemDevicedDisplay *_auto_gen_org_tizen_system_deviced_display_proxy_new_for_bus_finish (
    GAsyncResult        *res,
    GError             **error);
_auto_genOrgTizenSystemDevicedDisplay *_auto_gen_org_tizen_system_deviced_display_proxy_new_for_bus_sync (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error);


/* ---- */

#define _AUTO_GEN_TYPE_ORG_TIZEN_SYSTEM_DEVICED_DISPLAY_SKELETON (_auto_gen_org_tizen_system_deviced_display_skeleton_get_type ())
#define _AUTO_GEN_ORG_TIZEN_SYSTEM_DEVICED_DISPLAY_SKELETON(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), _AUTO_GEN_TYPE_ORG_TIZEN_SYSTEM_DEVICED_DISPLAY_SKELETON, _auto_genOrgTizenSystemDevicedDisplaySkeleton))
#define _AUTO_GEN_ORG_TIZEN_SYSTEM_DEVICED_DISPLAY_SKELETON_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), _AUTO_GEN_TYPE_ORG_TIZEN_SYSTEM_DEVICED_DISPLAY_SKELETON, _auto_genOrgTizenSystemDevicedDisplaySkeletonClass))
#define _AUTO_GEN_ORG_TIZEN_SYSTEM_DEVICED_DISPLAY_SKELETON_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), _AUTO_GEN_TYPE_ORG_TIZEN_SYSTEM_DEVICED_DISPLAY_SKELETON, _auto_genOrgTizenSystemDevicedDisplaySkeletonClass))
#define _AUTO_GEN_IS_ORG_TIZEN_SYSTEM_DEVICED_DISPLAY_SKELETON(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), _AUTO_GEN_TYPE_ORG_TIZEN_SYSTEM_DEVICED_DISPLAY_SKELETON))
#define _AUTO_GEN_IS_ORG_TIZEN_SYSTEM_DEVICED_DISPLAY_SKELETON_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), _AUTO_GEN_TYPE_ORG_TIZEN_SYSTEM_DEVICED_DISPLAY_SKELETON))

typedef struct __auto_genOrgTizenSystemDevicedDisplaySkeleton _auto_genOrgTizenSystemDevicedDisplaySkeleton;
typedef struct __auto_genOrgTizenSystemDevicedDisplaySkeletonClass _auto_genOrgTizenSystemDevicedDisplaySkeletonClass;
typedef struct __auto_genOrgTizenSystemDevicedDisplaySkeletonPrivate _auto_genOrgTizenSystemDevicedDisplaySkeletonPrivate;

struct __auto_genOrgTizenSystemDevicedDisplaySkeleton
{
  /*< private >*/
  GDBusInterfaceSkeleton parent_instance;
  _auto_genOrgTizenSystemDevicedDisplaySkeletonPrivate *priv;
};

struct __auto_genOrgTizenSystemDevicedDisplaySkeletonClass
{
  GDBusInterfaceSkeletonClass parent_class;
};

GType _auto_gen_org_tizen_system_deviced_display_skeleton_get_type (void) G_GNUC_CONST;

_auto_genOrgTizenSystemDevicedDisplay *_auto_gen_org_tizen_system_deviced_display_skeleton_new (void);


G_END_DECLS

#endif /* __AUTO_GEN_INTERFACE_H__ */
